### ISSUE TITLE
Linha base no gráfico de Grantt

### ISSUE THREAD

**Issue by EdersonCR** [GeraldoOliveira/financiamento_unifei#1]
Foi definida a linha base do cronograma definitivo no MS Project, porém o gráfico de Grantt não está exibindo a linha base.
Modificar o cronograma no MS Project para exibir a linha base no gráfico de Grantt.

**Comment by GeraldoOliveira** [comment]
Resolvido: Clicar com o botão direito em cima do grafico de Grantt > Mostrar/Ocultar Estilo de Barra > Linha de Base > Selecionar a linha de base salva.
