### ISSUE TITLE
Validação de sessão

### ISSUE THREAD

**Issue by EdersonCR** [GeraldoOliveira/financiamento_unifei#3]
O sistema não está realizando validação de sessão. Sem fazer login, pela URL no browser o usuário consegue acessar outra páginas do sistema

**Comment by GeraldoOliveira** [comment]
Caso a sessao nao esteja iniciada, ao tentar acessar alguma outra pagina do sistema, será encaminhado para a pagina de login para se realizar o login ou criar o cadastro.
